spring:
  banner:
    image:
#      location: static/favicon.ico
#      bitdepth: 4
mybatis:
  configuration:
    map-underscore-to-camel-case: true
page helper:
#  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#  dialect: mysql
  auto-dialect: true