
server:
  port: 8181
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/meta?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: mike
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  banner:
    image:
#      location: static/favicon.ico
#      bitdepth: 4

mybatis:
  configuration:
    map-underscore-to-camel-case: true
page helper:
#  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#  dialect: mysql
  auto-dialect: true
